name: plus_downloader
description: A Downloader.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1
  meta: ^1.1.8
  equatable: ^1.2.0
  file: ^5.1.0
  youtube_explode_dart: ^1.0.0
  path: ^1.7.0
  dio: ^3.0.9

dev_dependencies:
  test: ^1.6.0
  mockito: ^4.1.1