name: example
description: Example of Generator
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  plus_generator:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.1

flutter:
  uses-material-design: true
