name: plus_dart
description: Auto Generator for Flutter Project.
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  uuid: ^2.0.4

dev_dependencies:
  dart_style: ^1.3.4
  build_runner: ^1.8.1
  source_gen: ^0.9.5
  code_builder: ^3.2.1
