name: example
description: Example of Generator
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  plus_redux:
    path: ../../packages/redux/core

dev_dependencies:
  flutter_test:
    sdk: flutter

  plus_redux_generator:
    path: ../../packages/redux/generator
  
  build_runner: ^1.8.1

flutter:
  uses-material-design: true
