builders:
  reduxReducerProviderGenerator:
    import: "package:plus_redux_generator/builders.dart"
    builder_factories: ["reduxReducerProviderGenerator"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: cache

  reduxStoreGenerator:
    import: "package:plus_redux_generator/builders.dart"
    builder_factories: ["reduxStoreGenerator"]
    build_extensions: {".dart": [".p.dart"]}
    auto_apply: dependents
    build_to: source