name: plus_redux_generator
description: Redux Generator.
version: 0.0.3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  uuid: ^2.0.4
  dart_style: ^1.3.4
  build_runner:
    path: ../../build/build_runner
  source_gen: ^0.9.5
  code_builder: ^3.2.1
